import "./globals.css";
import Header from "../components/header";
import Sidebar from "../components/sidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        
        <div className="flex h-screen">
          <Sidebar></Sidebar>
          

          <div className="h-full bg-blue-100 flex-grow">
            <h1 className="text-black">home page</h1>
            {children}
            </div>
            </div>
        

        <div className="bg-line-700">
          <h1>Footer</h1>
        </div>
      </body>
    </html>
  );
}
